### PR TITLE
Favicon and rule for bayern.de (5.x)

### PR DESCRIPTION
**Pull request by dodmi**

### CODE REVIEW

**Review by lieser — COMMENTED** [review]
From where did you get the icon? If I look at `bayern.de` a different one is shown (https://www.bayern.de/favicon.ico)

**Comment by dodmi** [comment]
Well, actually I didn't visit the website at all, but took an image of an Bavarian flag and cut out some part.
https://en.wikipedia.org/wiki/Flag_of_Bavaria
But there are two flags...
While 
www.bayern.de uses https://www.bayern.de/favicon.ico
www.stmi.bayern.de uses https://www.stmi.bayern.de/odeon_assets/images/favicon/favicon.ico, which is similar to my image (and which probably most people associate with Bavaria).

Shall I change the image to https://www.bayern.de/favicon.ico instead?

**Comment by lieser** [comment]
> Shall I change the image to https://www.bayern.de/favicon.ico instead?

I would tend to say yes. I agree with you that the current image is probably easier associated with Bavaria, but so far we tended to always use the favicon of the associated website, in the hope they know best which Image they think represents them.

Note that separate images vor Subdomains are possible.

**Comment by dodmi** [comment]
I've changed the icon. You're right, it's much easier to always use the icon from the domain.

**Review by lieser — APPROVED** [review]

**Pull request merged**
