### PR TITLE
Updated German translation

### PR DESCRIPTION
**Pull request by dodmi**
This translation is a proposal, as it's different from your change in master. I think, this text is easier to understand :)

### CODE REVIEW

**Review by lieser — APPROVED** [review]
Thanks, will do the same change to master

**Comment by lieser** [comment]
A small note on your git usage. The way you seem to use it at least to me looks sup-optimal.
Note that for me it is fine if you continue to use it in the same way. I just want to make sure you do it because it is what works best for you, and not because you are unaware of other options.

Currently you have a `2.x` branch in your repository (will call this `dodmi:2.x`), which you keep up to date by always merging my upstream `2.x` branch (`lieser:2.x`) into it.
And if you start to work on a feature, you start you feature branch (e.g. `dodmi:updTrans-de-2.x-sigerrors`) on your `dodmi:2.x` branch.

If you look just at the code it does not make a difference, because the diff of all the files between `dodmi:2.x` and `lieser:2.x` is empty after your merged `lieser:2.x` into  `dodmi:2.x`.

But the git commits of both branches, which are essentially show the history how the code came to be, are different.
This is e.g. the reason the pull request you create here like this one show a lot of unrelated commits, which are in your `dodmi:2.x` branch, but are not in my `lieser:2.x` branch.

A cleaner way would be to let your feature branches start from the branch you want to merge into, i.e. `lieser:2.x` and not `dodmi:2.x`.

If you still want a `2.x` branch in your repository that is essentially a mirror of my upstream `2.x` branch, you could still have that (After you deleted your current one, or maybe just use a different name for trying it out).
But if your update your branch by pulling `lieser:2.x`, make sure it is just doing a fast-forward instead of doing a merge and creating a merge commit. Otherwise the commit history between both branches would again be different, even if the file content is the same.

**Comment by dodmi** [comment]
Thank you. Actually, I'd prefer not having the history in the pull requests and I simply didn't understand, why this happened.
I tried pulling the changes from your lieser:2.x branch (without the history) and push it to my dodmi:2x branch in repository, but this didn't do it.
I had a look into https://www.git-scm.com/docs/git-pull and as I understand, I should run "git pull --rebase" or "git fetch" and "git rebase" to get rid of the unneeded history? Or would it be "git pull -ff".

At the moment, I've an additional (local) branch, where I started to backport your internationalization support. But I'm not sure if I'll finish it for the 2.x branch.

Thank you for your help :) I'll try it the next time.

**Comment by lieser** [comment]
The easiest way to get `dodmi:2.x` back into the same state as `lieser:2.x` is to use the [`git reset`](https://www.git-scm.com/docs/git-reset) command. It is however important to keep in mind that this is a destructive command and will discard the history and in hard mode also your changes.

E.g. assuming you have added my upstream repository under the remote name `lieser`:
```bash
# If you are currently on a different brach,
# checkout the branch you want to reset, i.e. your local 2.x
git checkout 2.x

# Do a default mixed reset (changed files are preserved)
git reset lieser/2.x
# Or do a hard reset (any changes are discarded!)
git reset --hard lieser/2.x
```

If you are new to git it is probably also helpful to visualize the branches and commits. E.g. with the GUI git also provides by calling `gitk --all`. More about it at https://www.git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Graphical-Interfaces.

**Comment by lieser** [comment]
Forgot to add:
After the git reset both `lieser:2.x` and `dodmi:2.x` have the same history. If the `lieser:2.x` branch then advances because I e.g. merge one of your pull request a git pull with fast forward should work too.

But if for some reason `dodmi:2.x` will again have a different history from `lieser:2.x`, e.g. because you by accident created a merge commit instead of doing a fast forward, fast forwarding will no longer work. And you will have to do a reset again.

**Pull request merged**
