### PR TITLE
Translate de 2.x improvements 2023-01-25

### PR DESCRIPTION
**Pull request by dodmi**
Understood the error message wrong, so tried to improve the message (and added a dash)

### CODE REVIEW

**Comment by lieser** [comment]
Thanks for the feedback, have to think about the change a little, and would then also adopt the message on master.

But if the current message for `DKIM_POLICYERROR_MISSING_SIG` can be misleading the english reference string has to be probably adapted to (and i.e. also the translations, but that is probably overkill for the 2.x version).

**Comment by dodmi** [comment]
Well, my first thought after reading the error was, that the mail is signed, but from another domain. So, I changed the text, to express, that there is no signature at all.
I can also change the English string myself. For other languages, I'd leave it as it is, until I could backport it from the master branch.

**Comment by dodmi** [comment]
Well, should I change the English version, too? Or don't you like to change it anyway?

**Comment by lieser** [comment]
Sry for the late reply. Fought about it again and agree that this is probably a good change. Will do the same change on master.

Unless you have a better suggestion I would change the English to `No Signature, should be signed by $1`.

**Comment by dodmi** [comment]
No, I haven't a better suggestion :)

**Review by lieser — APPROVED** [review]
Thanks for the improvement, I will do the same on master.

**Pull request merged**
