### PR TITLE
Removed use of toType function

### PR DESCRIPTION
**Pull request by dodmi**

### CODE REVIEW

**Review by lieser — APPROVED** [review]
LGTM, but just want to make sure you tested the DMARC functionality with this change?

If I remember correctly in some old version I needed to use the `toType(...)` helper becasue for some reason the `instanceof` was not reporting the `Map` type.
No idea since when this is no longer needed.

**Comment by dodmi** [comment]
Well, mainly I tested, that `instanceof Map` returns `true` for maps and `false` integers.
Is there an example in your test files?

**Comment by lieser** [comment]
You should really test the future. If I remember it correctly the problem was related with the Map not bein created in the same JSM module that the `instanceof` was,

1. Disable default sign rules
2. Enable DMARC https://github.com/lieser/dkim_verifier/wiki/Options#use-dmarc-to-heuristically-determine-if-an-e-mail-should-be-signed
3. With an e-mail form a domain that has DMARC, and there you don't have a sign rule. E.g. from GitGub.
4. Look in the logs that a DMARC policy was found and the record was parsed. The log should also indicate that the message needs to be signed even if no rule was found (`Object { shouldBeSigned: true, sdid: (1) […], foundRule: false, hideFail: false }`)

**Comment by dodmi** [comment]
Thank you for your assistance. 
I can confirm, that instanceof doesn't work here. So, I'm closing this pull request.
And yes - I'm trying to test my changes as good as I can. Thank you for the hint, that I can include the DNS keys into the database. Now, I can test against your sample files from master. That's really a big step (at least for me)

**Pull request closed without merging**
