### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by DavidBrazSan**
I wanted to help locate this extension in my country.

### CODE REVIEW

**Review by lieser — APPROVED** [review]

**Comment by lieser** [comment]
Thanks a lot for contributing the translation.

I will add you to the Translators in the about page of the addon. Please let me know if you want to be credited with something different than the name on your GitHub profile.

**Comment by DavidBrazSan** [comment]
You can use the user.

**Comment by lieser** [comment]
Added you to the about page and removed some trailing comma in the JSON file, which Thunderbird does not allow (325940e1c2c39d18e03ac096cf73dd72caab89d6).

**Comment by lieser** [comment]
Note that I now also added your translation to https://addons.thunderbird.net/pt-br/thunderbird/addon/dkim-verifier/

**Pull request merged**
