### PR TITLE
Add CI for 2.x

### PR DESCRIPTION
**Pull request by lieser**
This adds a ESLint and Type Check for the 2.x branch.

Enabling and fixing strict type checking is left for a follow up.

### CODE REVIEW

**Comment by dodmi** [comment]
As always, thank you :)
The problem is, I have no experience with Type Script and ESlint, I'm not a developer. 
For useful testing, you'll need useful tests and I'm far away from writing such tests. I think, I'll probably need a lot of time to get into it.

**Comment by lieser** [comment]
> The problem is, I have no experience with Type Script and ESlint, I'm not a developer.

That is not a problem as long as you are willing to learn.

With the help of JSDoc comments and the Type Script compiler you can make Java Script feel more like a statically typed language.

The advantages are:

- Easier to find errors there variables have a different type than you may have expected.
- Better development experience because the IDE can show you what type a variable has or that type a function expects as a parameter. See e.g. my screenshot above.

See also https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html and https://code.visualstudio.com/Docs/languages/javascript#_type-checking.

ESLint (https://eslint.org/) is a statically analyzes the code to:

- Find potential problems
- Enforce some best practices for writing code

As you don't seem to have any objections I will merge this now.
My recommendation would be for you to start using VS Code if you are not doing that already. And just try out the ESlint and type checking integration, and hopefully see how it improves your development experience.

1. Install VS Code https://code.visualstudio.com/
2. Install Node.js https://nodejs.org
3. Run `npm ci` in the root of the repository to install Node.js dependencies
4. Open the folder in VS Code
5. Install the recommended extensions (at least https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
6. Start developing

**Comment by dodmi** [comment]
Well, I'm really interested and would like to learn. So, I'll give it a try. I'm not using "VS Code". As I'm no developer, I have no full blown IDE, but only Notepad++, which provides syntax highlighting and a function list. So, I'll need some time to get into it (thank you for the links and quick steps to get it working)

**Comment by lieser** [comment]
Yesterday I found some errors then I wanted to merge it, fixed it now (and force pushed this branch).

**Pull request merged**
